name: behaviour
description:
  This package adds support for behaviours. Behaviours are classes of which the
  instances are used as functions.
version: 0.0.3
repository: https://github.com/wim07101993/behaviour

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  async: ">=2.0.0 <3.0.0"

dev_dependencies:
  faker: ">=2.0.0 <3.0.0"
  lint: 
  mocktail: ">0.0.0 <1.0.0"
  test: ">=1.0.0 <2.0.0"
