name: behaviour
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  async:

dev_dependencies:
  faker:
  lint:
  mocktail:
  test:

dependency_overrides:
  meta: 1.6.0
