name: behaviour
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  async: ^2.8.2

dev_dependencies:
  faker: ^2.0.0
  lint: ^1.7.2
  mocktail: ^0.2.0
  test: ^1.19.3