name: behaviour
description:
  This package adds support for behaviours. Behaviours are classes of which the
  instances are used as functions.
version: 0.0.1+1
repository: https://github.com/wim07101993/behaviour

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  async: ^2.9.0

dev_dependencies:
  faker: ^2.0.0
  lint: ^1.8.2
  mocktail: ^0.3.0
  test: ^1.21.3
